#!/usr/bin/env node

console.log('Starting foo...');

var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('FOO');
}).listen(process.env.PORT, '127.0.0.1');
