name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 28.1
          - 29.1
    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Test the project
      run: |
        emacs --version
        make ci-dependencies
        nix shell \
          --extra-experimental-features flakes \
          --extra-experimental-features nix-command \
          nixpkgs#nodePackages.coffee-script \
          --command make check
